---
title: "0. eagrass Restoration STradeoffs Paper - Post Processing Spatial Datasets"
author: "Jennifer McHenry"
date: "7/21/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.pos = "H", out.extra = "")

#Load Libraries

library(tidyverse)
library(RColorBrewer)
library(mgcv)
library(tools)
library(viridis)
library(ggpubr)
# library(ggsn)
library(remotes)
library(raster)
library(sp)
library(rgdal)
# remotes::install_version("Rttf2pt1", version = "1.3.8")
library(extrafont)
library(ggcorrplot)
# extrafont::font_import() 
loadfonts("win")
library(ggplot2)
library(corrplot)
library(colorspace)
library(rgeos)

#Load Functions 
pal_teal_blue_purple <- rainbow(12)

odds_to_prob=function(x){
        prob<-exp(x)/(1+exp(x))
        return(prob)
}

#Setting Directory Paths
wd=getwd()

username=as.vector(strsplit(wd,"/"));names(username)<-c("username")

Saved_RData_Dir=paste("C:/Users/",username$username[3],"/Dropbox/GITHUB/Disseratation/",sep="")

```

#LOADING DATASETS FOR THE ANALYSIS 
```{r}

#SEAGRASS LAYERS######################################################################################
# Study area
study_area<-raster("input_data/study_area.tif")

#Total Predicted_Seagrass
Seagrass_Cover=raster(paste(Saved_RData_Dir,"Modeling_Biodiversity_Enhancement_Value/model_output/August_2020_seagrassmodel_predictions/Annual_Predictions/Seagrass_Cover_MeanAnnual_Current_Corrected_CorExp.tif",sep=""))
names(Seagrass_Cover)<-c("Seagrass_Cover")

Total_Predicted_Seagrass=Seagrass_Cover
Total_Predicted_Seagrass[Total_Predicted_Seagrass<5]<-NA
Total_Predicted_Seagrass[Total_Predicted_Seagrass>=5]<-1

Total_Predicted_Seagrass=mask(Total_Predicted_Seagrass,mask=study_area)

world_crs <- '+proj=longlat +datum=WGS84 +no_defs '

newproj <- '+proj=utm +zone=15 +ellps=GRS80 +datum=NAD83 +units=m +no_defs'

#creating a template for two scale analysis
Total_Predicted_Seagrass_1HA <- raster::projectRaster(from=Total_Predicted_Seagrass, crs=newproj, res=100,method = "bilinear")

Total_Predicted_Seagrass_1HA[is.na(Total_Predicted_Seagrass_1HA)!=TRUE]<-1

Total_Predicted_Seagrass_1KM <-aggregate(Total_Predicted_Seagrass_1HA, fact=10, fun=mean)

Total_Predicted_Seagrass_5KM <-aggregate(Total_Predicted_Seagrass_1KM, fact=5, fun=mean)

Total_Predicted_Seagrass_10KM <-aggregate(Total_Predicted_Seagrass_1KM, fact=10, fun=mean)


#finalizing the raster version
Total_Predicted_Seagrass_1HA_WGS <- raster::projectRaster(from=Total_Predicted_Seagrass_1HA,crs=world_crs)

Total_Predicted_Seagrass_1KM_WGS <- raster::projectRaster(from=Total_Predicted_Seagrass_1KM,crs=world_crs)

Total_Predicted_Seagrass_5KM_WGS <- raster::projectRaster(from=Total_Predicted_Seagrass_5KM,crs=world_crs)

Total_Predicted_Seagrass_10KM_WGS <- raster::projectRaster(from=Total_Predicted_Seagrass_10KM,crs=world_crs)


#Confirmed Seagrass Areas
Confirmed=raster("C:/Users/Jennifer/Dropbox/GITHUB/Disseratation/Modeling-Spatial-Variability-of-Ecosystem-Services-from-FLSeagrassBeds/input_data/seagrass_area_masks/confirmed_seagrass_beds.tif")
Confirmed=mask(Confirmed,mask = study_area)

#Potential recovery areas
PRAs=raster("input_data/seagrass_area_masks/potential_recovery_area.tif")
PRAs=mask(PRAs,mask = study_area)
```

# LOADING ECOSYSTEM SERVICE LAYERS - Confirmed Vs PRAs

```{r}
# Confirmed
#Loading ES Outputs (Standarized)
BioDiv_EV_Confirmed=raster("C:/Users/Jennifer/Dropbox/GITHUB/Disseratation/Modeling-Spatial-Variability-of-Ecosystem-Services-from-FLSeagrassBeds/input_data/ES-Model-Outputs/BioDiv_EV_Zscores_Confirmed.tif")
NurHab_EV_Confirmed=raster("C:/Users/Jennifer/Dropbox/GITHUB/Disseratation/Modeling-Spatial-Variability-of-Ecosystem-Services-from-FLSeagrassBeds/input_data/ES-Model-Outputs/NursHab_EV_Zscores_Confirmed.tif")
BlueCar_EV_Confirmed=raster("C:/Users/Jennifer/Dropbox/GITHUB/Disseratation/Modeling-Spatial-Variability-of-Ecosystem-Services-from-FLSeagrassBeds/input_data/ES-Model-Outputs/BC_Storage_EV_Zscores_Confirmed.tif")
RecTour_EV_Confirmed=raster("C:/Users/Jennifer/Dropbox/GITHUB/Disseratation/Modeling-Spatial-Variability-of-Ecosystem-Services-from-FLSeagrassBeds/input_data/ES-Model-Outputs/Rec_EV_Zscores_Confirmed.tif")
Expos_EV_Confirmed=raster("C:/Users/Jennifer/Dropbox/GITHUB/Disseratation/Modeling-Spatial-Variability-of-Ecosystem-Services-from-FLSeagrassBeds/input_data/ES-Model-Outputs/Exposure_EV_Zscores_Confirmed.tif")

ES_Zscores=stack(BioDiv_EV_Confirmed,NurHab_EV_Confirmed,BlueCar_EV_Confirmed,RecTour_EV_Confirmed,Expos_EV_Confirmed)

ES_Zscores_Confirmed=mask(ES_Zscores,mask=Confirmed)


# Potential Recovery Areas
#Loading ES Outputs (Standarized)
BioDiv_EV_PRAs=raster("input_data/ES-Model-Outputs/BioDiv_EV_Zscores_PRAs.tif")
NurHab_EV_PRAs=raster("input_data/ES-Model-Outputs/NursHab_EV_Zscores_PRAs.tif")
BlueCar_EV_PRAs=raster("input_data/ES-Model-Outputs/BC_Storage_EV_Zscores_PRAs.tif")
RecTour_EV_PRAs=raster("input_data/ES-Model-Outputs/Rec_EV_Zscores_PRAs.tif")
Expos_EV_PRAs=raster("input_data/ES-Model-Outputs/Exposure_EV_Zscores_PRAs.tif")
Pop_EV_PRAs=raster("input_data/ES-Model-Outputs/Population_EV_Zscores_PRAs.tif")

ES_Zscores_PRAs=stack(BioDiv_EV_PRAs,NurHab_EV_PRAs,BlueCar_EV_PRAs,RecTour_EV_PRAs,Expos_EV_PRAs)
ES_Zscores_PRAs=mask(ES_Zscores_PRAs,mask=PRAs)

```

# Parsing out two differnt sizes.
```{r}
# 1-hectare analysis stack
ES_Zscores_Confirmed_1HA<-resample(x= ES_Zscores_Confirmed, y=Total_Predicted_Seagrass_1HA_WGS)

ES_Zscores_Confirmed_1HA_df=as.data.frame(rasterToPoints(ES_Zscores_Confirmed_1HA))
names(ES_Zscores_Confirmed_1HA_df)<-c("x","y","BioDiv","NurHab","BlueCar","RecTour","Expos")
ES_Zscores_Confirmed_1HA_df<-ES_Zscores_Confirmed_1HA_df[complete.cases(ES_Zscores_Confirmed_1HA_df),]
summary(ES_Zscores_Confirmed_1HA_df)

ES_Zscores_PRAs_1HA<-resample(x= ES_Zscores_PRAs, y=Total_Predicted_Seagrass_1HA_WGS)

ES_Zscores_PRAs_1HA_df=as.data.frame(rasterToPoints(ES_Zscores_PRAs_1HA))
names(ES_Zscores_PRAs_1HA_df)<-c("x","y","BioDiv_PRAs","NurHab_PRAs","BlueCar_PRAs","RecTour_PRAs","Expos_PRAs")
ES_Zscores_PRAs_1HA_df<-ES_Zscores_PRAs_1HA_df[complete.cases(ES_Zscores_PRAs_1HA_df),]
summary(ES_Zscores_PRAs_1HA_df)


# 1-kilometer analysis stack
ES_Zscores_Confirmed_1KM<-resample(x= ES_Zscores_Confirmed, y=Total_Predicted_Seagrass_1KM_WGS)

ES_Zscores_Confirmed_1KM_df=as.data.frame(rasterToPoints(ES_Zscores_Confirmed_1KM))
names(ES_Zscores_Confirmed_1KM_df)<-c("x","y","BioDiv","NurHab","BlueCar","RecTour","Expos")
ES_Zscores_Confirmed_1KM_df<-ES_Zscores_Confirmed_1KM_df[complete.cases(ES_Zscores_Confirmed_1KM_df),]
summary(ES_Zscores_Confirmed_1KM_df)

ES_Zscores_PRAs_1KM<-resample(x= ES_Zscores_PRAs, y=Total_Predicted_Seagrass_1KM_WGS)

ES_Zscores_PRAs_1KM_df=as.data.frame(rasterToPoints(ES_Zscores_PRAs_1KM))
names(ES_Zscores_PRAs_1KM_df)<-c("x","y","BioDiv_PRAs","NurHab_PRAs","BlueCar_PRAs","RecTour_PRAs","Expos_PRAs")
ES_Zscores_PRAs_1KM_df<-ES_Zscores_PRAs_1KM_df[complete.cases(ES_Zscores_PRAs_1KM_df),]
summary(ES_Zscores_PRAs_1KM_df)

# 5-kilometer analysis stack
ES_Zscores_Confirmed_5KM<-resample(x= ES_Zscores_Confirmed, y=Total_Predicted_Seagrass_5KM_WGS)

ES_Zscores_Confirmed_5KM_df=as.data.frame(rasterToPoints(ES_Zscores_Confirmed_5KM))
names(ES_Zscores_Confirmed_5KM_df)<-c("x","y","BioDiv","NurHab","BlueCar","RecTour","Expos")
ES_Zscores_Confirmed_5KM_df<-ES_Zscores_Confirmed_5KM_df[complete.cases(ES_Zscores_Confirmed_5KM_df),]
summary(ES_Zscores_Confirmed_5KM_df)

ES_Zscores_PRAs_5KM<-resample(x= ES_Zscores_PRAs, y=Total_Predicted_Seagrass_5KM_WGS)

ES_Zscores_PRAs_5KM_df=as.data.frame(rasterToPoints(ES_Zscores_PRAs_5KM))
names(ES_Zscores_PRAs_5KM_df)<-c("x","y","BioDiv_PRAs","NurHab_PRAs","BlueCar_PRAs","RecTour_PRAs","Expos_PRAs")
ES_Zscores_PRAs_5KM_df<-ES_Zscores_PRAs_5KM_df[complete.cases(ES_Zscores_PRAs_5KM_df),]
summary(ES_Zscores_PRAs_5KM_df)

# 10-kilometer analysis stack
ES_Zscores_Confirmed_10KM<-resample(x= ES_Zscores_Confirmed, y=Total_Predicted_Seagrass_10KM_WGS)

ES_Zscores_Confirmed_10KM_df=as.data.frame(rasterToPoints(ES_Zscores_Confirmed_10KM))
names(ES_Zscores_Confirmed_10KM_df)<-c("x","y","BioDiv","NurHab","BlueCar","RecTour","Expos")
ES_Zscores_Confirmed_10KM_df<-ES_Zscores_Confirmed_5KM_df[complete.cases(ES_Zscores_Confirmed_10KM_df),]
summary(ES_Zscores_Confirmed_10KM_df)

ES_Zscores_PRAs_10KM<-resample(x= ES_Zscores_PRAs, y=Total_Predicted_Seagrass_10KM_WGS)

ES_Zscores_PRAs_10KM_df=as.data.frame(rasterToPoints(ES_Zscores_PRAs_10KM))
names(ES_Zscores_PRAs_10KM_df)<-c("x","y","BioDiv_PRAs","NurHab_PRAs","BlueCar_PRAs","RecTour_PRAs","Expos_PRAs")
ES_Zscores_PRAs_10KM_df<-ES_Zscores_PRAs_10KM_df[complete.cases(ES_Zscores_PRAs_10KM_df),]
summary(ES_Zscores_PRAs_10KM_df)

```


# Saving output
```{r}
rm(list= ls()[!(ls() %in% c("Total_Predicted_Seagrass","PRAs","Confirmed","Total_Predicted_Seagrass_1HA_WGS","Total_Predicted_Seagrass_1KM_WGS","Total_Predicted_Seagrass_5KM_WGS","Total_Predicted_Seagrass_10KM_WGS","ES_Zscores_PRAs_1HA","ES_Zscores_PRAs_1HA_df","ES_Zscores_Confirmed_1HA","ES_Zscores_Confirmed_1HA_df","ES_Zscores_PRAs_1KM","ES_Zscores_PRAs_1KM_df","ES_Zscores_Confirmed_1KM","ES_Zscores_Confirmed_1KM_df", "ES_Zscores_Confirmed_5KM", "ES_Zscores_Confirmed_5KM_df","ES_Zscores_PRAs_5KM","ES_Zscores_PRAs_5KM_df", "ES_Zscores_PRAs_10KM", "ES_Zscores_PRAs_10KM_df", "ES_Zscores_Confirmed_10KM","ES_Zscores_Confirmed_10KM_df"))])

writeRaster(PRAs,file="processed_datasets/PRAs.tif",overwrite=TRUE)
writeRaster(Confirmed,file="processed_datasets/Confirmed_Beds.tif",overwrite=TRUE)
writeRaster(Total_Predicted_Seagrass,file="processed_datasets/Total_Predicted_Seagrass.tif",overwrite=TRUE)
writeRaster(Total_Predicted_Seagrass_1HA_WGS,file="processed_datasets/Total_Predicted_Seagrass_1HA_WGS.tif",overwrite=TRUE)
writeRaster(Total_Predicted_Seagrass_1KM_WGS,file="processed_datasets/Total_Predicted_Seagrass_1KM_WGS.tif",overwrite=TRUE)

# 1- HECTARE OUTPUT
write.csv(ES_Zscores_PRAs_1HA_df,file = "processed_datasets/ES_Zscores_PRAs_1HA.csv")
# 
writeRaster(ES_Zscores_PRAs_1HA,file=paste("processed_datasets/",names(ES_Zscores_PRAs_1HA),"_1HA.tif",sep=""),bylayer=TRUE, overwrite=TRUE)

write.csv(ES_Zscores_Confirmed_1HA_df,file = "processed_datasets/ES_ZScores_Confirmed_1HA.csv")
# 
writeRaster(ES_Zscores_Confirmed_1HA,file=paste("processed_datasets/",names(ES_Zscores_Confirmed_1HA),"_1HA.tif",sep=""),bylayer=TRUE,overwrite=TRUE)

# 1- SQKM OUTPUT
write.csv(ES_Zscores_PRAs_1KM_df,file = "processed_datasets/ES_Zscores_PRAs_1KM.csv")
# 
writeRaster(ES_Zscores_PRAs_1KM,file=paste("processed_datasets/",names(ES_Zscores_PRAs_1KM),"_1KM.tif",sep=""),bylayer=TRUE,overwrite=TRUE)

write.csv(ES_Zscores_Confirmed_1KM_df,file = "processed_datasets/ES_ZScores_Confirmed_1KM.csv")
# 
writeRaster(ES_Zscores_Confirmed_1KM,file=paste("processed_datasets/",names(ES_Zscores_Confirmed_1KM),"_1KM.tif",sep=""),bylayer=TRUE,overwrite=TRUE)

# 5- SQKM OUTPUT
write.csv(ES_Zscores_PRAs_5KM_df,file = "processed_datasets/ES_Zscores_PRAs_5KM.csv")
# 
writeRaster(ES_Zscores_PRAs_5KM,file=paste("processed_datasets/",names(ES_Zscores_PRAs_5KM),"_5KM.tif",sep=""),bylayer=TRUE,overwrite=TRUE)

write.csv(ES_Zscores_Confirmed_5KM_df,file = "processed_datasets/ES_ZScores_Confirmed_5KM.csv")
# 
writeRaster(ES_Zscores_Confirmed_5KM,file=paste("processed_datasets/",names(ES_Zscores_Confirmed_5KM),"_5KM.tif",sep=""),bylayer=TRUE,overwrite=TRUE)


# 10- SQKM OUTPUT
write.csv(ES_Zscores_PRAs_10KM_df,file = "processed_datasets/ES_Zscores_PRAs_10KM.csv")
# 
writeRaster(ES_Zscores_PRAs_10KM,file=paste("processed_datasets/",names(ES_Zscores_PRAs_1KM),"_10KM.tif",sep=""),bylayer=TRUE,overwrite=TRUE)

write.csv(ES_Zscores_Confirmed_10KM_df,file = "processed_datasets/ES_ZScores_Confirmed_10KM.csv")
# 
writeRaster(ES_Zscores_Confirmed_10KM,file=paste("processed_datasets/",names(ES_Zscores_Confirmed_10KM),"_5KM.tif",sep=""),bylayer=TRUE,overwrite=TRUE)

save.image(file = "processed_datasets/ES_ZScores_PRAs_Spatial_Layers.RData")
```

