---
title: "1. Seagrass Restoration Trade-offs Paper - Spatial Analysis & Plotting"
author: "Jennifer McHenry"
date: "07/21/2022"
output: 
  pdf_document:
    extra_dependencies: float 
    toc: yes
    fig_width: 8
    fig_height: 6
    fig_caption: yes
---


```{r setup, include=FALSE,fig.height=6}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.pos = "H", out.extra = "")

#Load Libraries
library(tidyverse)
library(raster)
library(RColorBrewer)
library(viridis)
library(ggpubr)
# library(ggsn)
# library(remotes)
# remotes::install_version("Rttf2pt1", version = "1.3.8")
# library(extrafont)
# library(ggcorrplot)
# extrafont::font_import() 
# loadfonts("win")
# library(ggplot2)
# library(corrplot)
# library(colorspace)
# library(rgeos)

#Load Functions 
pal_teal_blue_purple <- rainbow(12)


#Setting Directory Paths
wd=getwd()

username=as.vector(strsplit(wd,"/"));names(username)<-c("username")

Saved_RData_Dir=paste("C:/Users/",username$username[3],"/Dropbox/GITHUB/Disseratation/",sep="")
```

# Visualizing Tradeoffs  plots of services 
```{r}

#Loading Data
load("processed_datasets/ES_ZScores_PRAs_Spatial_Layers.RData")

#Notes:
#SL - "Pairwise plots for every service combination: We’ve already looked at correlations, but these plots could allow us to look at the shape of the relationship and see whether there are opportunities for service “win-wins” even for negatively associated services (e.g. coastal protection and blue carbon)"

  #Hectare Scale
  
  #Stretches of the Coast
  # i.e., a larger grid scale like 10 square km.

#SL - "Is there a way to do this in a more multi-dimensional way (not just pairwise)....that’s essentially what figure 2 (or Fig 3.2) does by counting up service hotspots, so maybe there isn’t a new angle" 

  #PCA of Z Scores
    #Might not handle zscores well. 
    #Dont need to plot all the points. We just care about the lotations and the loadings. 
    #First experiment with a spatial PCA to see what it gives us. 

  #Convexity metrics? 

# L -In the current paper, we just look at service associations for existing seagrass beds….we could look at the restoration areas and see if different patterns emerge?

```

## Pairwise plots of services 
```{r fig.cap= ""}
##Pearson Correlations 
ES_cors_df<-ES_Zscores_df

names(ES_cors_df)<-c("Longitude","Latitude","Regions","Total Seagrass Cover","Biodiversity","Nursery Habitat","Gray Snapper","Lane Snapper","White Grunt","Spotted Seatrout","Sheepshead","Pink Shrimp","Blue Carbon","Recreation","Coastal Protection","Coastal Population")

#main ecosystem services
# ES_cors<-round(cor(ES_cors_df[c(5:6,13:16)]),1)
ES_cors<-round(cor(ES_cors_df[c(5:6,13:15)]),1)

ES_cors


#saving the output
tiff("plots/Figure_1.tiff", units="in", width=5, height=5, res=300)

corrplot(ES_cors, type = 'lower', order = 'original', tl.col = 'black',
         cl.ratio = 0.2, tl.srt = 45, col = diverge_hcl(8,h=c(190,290),l=c(40,95)),addCoef.col = 'black',diag=FALSE)

dev.off()



#expanded nursery habita tand other services
ES_cors_expanded<-round(cor(ES_cors_df[c(5,7:15)]),2)
ES_cors_expanded

#saving the output
tiff("plots/Figure_2.tiff", units="in", width=7, height=7, res=300)
corrplot(ES_cors_expanded, type = 'lower', order = 'original', tl.col = 'black',
         cl.ratio = 0.2, tl.srt = 45, col = diverge_hcl(8,h=c(190,290),l=c(40,95)),addCoef.col = 'black',diag=FALSE)
dev.off()

```

## Multi-dimensional plot of service bundles 
```{r fig.cap= ""}
# height interpreted in inches
```

## Correlation matrix or Pairwise plots compaarison - Restoration vs Confirmed? 
```{r fig.cap= ""}
# height interpreted in inches
```



